openapi: 3.0.2
info:
  version: '1.0'
  title: 'Display Lab Templates'
  description: An externalized templates.json file meant to be used in the precision feedback pipeline
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /displaylab/templates
    description: An externalized templates.json file meant to be used in the precision feedback pipeline
tags:
  - name: Display Lab Templates
    description: An externalized templates.json file meant to be used in the precision feedback pipeline
paths:
  /templates:
    get:
      parameters:
        - in: query
            name: v
            schema:
              type: string
              default:
                $ref: '#/info/version'
            required: true
            description: the api version of the endpoint
      tags:
        - Display Lab Templates
      description: An externalized templates.json file meant to be used in the precision feedback pipeline
      operationId: templates
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
